# Generated by Django 3.0.4 on 2021-01-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200929_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/images/userprofile.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Admitted', 'Admitted'), ('Under treatment', 'Under treatment'), ('Discharged', 'Discharged')], max_length=200, null=True),
        ),
    ]
